import {
  AlertItem,
  DashboardOverview,
  DomainHealth,
  IdentitySummary,
  MessageSummary,
  SeedInboxSummary,
  SeedPreview,
  SeedTestRunSummary,
  TemplateSummary,
} from '@/lib/types';

export const mockOverview: DashboardOverview = {
  totalOpens: 305,
  uniqueIds: 11,
  mostActive: { id: 'tony_public', count: 135 },
  latestOpen: { user: 'tony_local', timestamp: '2025-08-06T15:45:07' },
  topUsers: [
    { id: 'tony_public', count: 135 },
    { id: 'tony_local', count: 113 },
    { id: 'tony_localhost', count: 36 },
    { id: 'test', count: 10 },
    { id: 'hidden_click', count: 4 },
  ],
  recentOpens: [
    { user: 'tony_local', timestamp: '2025-08-06T15:45:07' },
    { user: 'tony_public', timestamp: '2025-08-06T15:45:07' },
    { user: 'hidden_click', timestamp: '2025-08-06T15:45:06' },
    { user: 'tony_local', timestamp: '2025-08-06T14:49:21' },
    { user: 'tony_public', timestamp: '2025-08-06T14:49:21' },
  ],
  activity: [
    { date: 'Aug 01', opens: 4 },
    { date: 'Aug 02', opens: 7 },
    { date: 'Aug 03', opens: 19 },
    { date: 'Aug 04', opens: 41 },
    { date: 'Aug 05', opens: 88 },
    { date: 'Aug 06', opens: 146 },
    { date: 'Today', opens: 0 },
  ],
};

export const mockMessages: MessageSummary[] = [
  {
    id: 'msg-launch-proof',
    subject: 'TokenTap launch note with tracked CTA',
    preview: 'Founder-style launch email with plain-text fallback and branded CTA block.',
    identity: 'tonyblum@me.com',
    status: 'Sent',
    recipients: 24,
    sentAt: '2026-03-07T09:15:00-07:00',
    opens: 18,
    clicks: 12,
    replies: 2,
    conversions: 1,
    notes: 'Good benchmark for future Apple SMTP templates.',
  },
  {
    id: 'msg-ws-seed',
    subject: 'Wheat & Stone proof suite seed test',
    preview: 'Pre-send validation run aimed at Gmail, Outlook, Yahoo, and iCloud seeds.',
    identity: 'info@wheatandstone.ca',
    status: 'Needs Review',
    recipients: 8,
    sentAt: '2026-03-07T08:25:00-07:00',
    opens: 0,
    clicks: 0,
    replies: 0,
    conversions: 0,
    notes: 'Blocked on automated inbox placement capture.',
  },
  {
    id: 'msg-pulse-bridge',
    subject: 'Pulse campaign teaser with follow-up ladder',
    preview: 'Draft sequence concept that will eventually sync with Pulse social launches.',
    identity: 'info@wheatandstone.ca',
    status: 'Draft',
    recipients: 0,
    sentAt: '2026-03-06T16:40:00-07:00',
    opens: 0,
    clicks: 0,
    replies: 0,
    conversions: 0,
    notes: 'Good candidate for campaign engine milestone.',
  },
];

export const mockIdentities: IdentitySummary[] = [
  {
    id: 'tony-me',
    label: 'Founder Rail',
    address: 'tonyblum@me.com',
    provider: 'Apple SMTP',
    health: 'healthy',
    lastSend: '2026-03-07 09:15',
    clickRate: '18.2%',
    replyRate: '4.1%',
    tracking: 'Soft opens + tracked links',
  },
  {
    id: 'ws-info',
    label: 'Brand Rail',
    address: 'info@wheatandstone.ca',
    provider: 'Apple Custom Domain',
    health: 'healthy',
    lastSend: '2026-03-07 08:25',
    clickRate: 'Pending',
    replyRate: 'Pending',
    tracking: 'Ready for seed suite',
  },
];

export const mockDomainHealth: DomainHealth[] = [
  {
    domain: 'me.com',
    spf: 'pass',
    dkim: 'pass',
    dmarc: 'pass',
    mx: 'pass',
    readiness: 'High confidence for founder-style sends',
    notes: 'Apple-hosted identity. Keep content lean and personal.',
  },
  {
    domain: 'wheatandstone.ca',
    spf: 'pass',
    dkim: 'pass',
    dmarc: 'pass',
    mx: 'pass',
    readiness: 'Healthy authentication baseline for tracked sends.',
    notes: 'Custom-domain rail aligned through iCloud Mail.',
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: 'alert-auth',
    level: 'info',
    title: 'Admin auth layer active',
    body: 'Dashboard access now sits behind the TMail admin session and same-origin proxy.',
  },
  {
    id: 'alert-seeds',
    level: 'info',
    title: 'Seed lab needs real inboxes',
    body: 'Configure real Gmail, Outlook, Yahoo, and iCloud addresses to turn the seed matrix into a real inbox-placement workflow.',
  },
];

export const mockSeedPreview: SeedPreview[] = [
  { provider: 'Gmail', accepted: 'Yes', placement: 'Inbox', render: 'Clean' },
  { provider: 'Outlook', accepted: 'Yes', placement: 'Pending', render: 'Pending' },
  { provider: 'Yahoo', accepted: 'Pending', placement: 'Pending', render: 'Pending' },
  { provider: 'iCloud', accepted: 'Pending', placement: 'Pending', render: 'Pending' },
];

export const mockTemplates: TemplateSummary[] = [
  {
    id: 'tpl-founder-note',
    name: 'Founder Note',
    slug: 'founder-note',
    category: 'Founder',
    description: 'A short founder note with a clean CTA and direct tone.',
    subject: 'Quick founder note from Tony',
    preheader: 'A short, direct note sent through TMail.',
    htmlBody: '<html><body><p>Hey there,</p><p>I wanted to send a quick note directly and keep it simple.</p><p><a href="https://wheatandstone.ca">Open the destination page</a></p><p>Tony</p></body></html>',
    textBody: 'Hey there,\n\nI wanted to send a quick note directly and keep it simple.\n\nOpen the destination page: https://wheatandstone.ca\n\nTony',
    isActive: true,
    createdAt: '2026-03-07T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
    versionCount: 3,
    currentVersion: 3,
  },
  {
    id: 'tpl-seed-lab',
    name: 'Seed Lab Probe',
    slug: 'seed-lab-probe',
    category: 'Testing',
    description: 'Minimal test message for inbox placement checks and render verification.',
    subject: 'TMail seed test probe',
    preheader: 'Seed inbox validation run from TMail.',
    htmlBody: '<html><body><p>This is a TMail seed test probe.</p><p><a href="https://api.tmail.tokentap.ca/healthz">Check the public API health endpoint</a></p></body></html>',
    textBody: 'This is a TMail seed test probe.\n\nCheck the public API health endpoint: https://api.tmail.tokentap.ca/healthz',
    isActive: true,
    createdAt: '2026-03-07T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
    versionCount: 2,
    currentVersion: 2,
  },
];

export const mockSeedInboxes: SeedInboxSummary[] = [
  {
    id: 'seed-gmail',
    provider: 'Gmail',
    label: 'Gmail Primary',
    emailAddress: '',
    notes: 'Configure a real Gmail seed inbox before enabling.',
    enabled: false,
    createdAt: '2026-03-07T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  {
    id: 'seed-outlook',
    provider: 'Outlook',
    label: 'Outlook Primary',
    emailAddress: '',
    notes: 'Configure a real Outlook seed inbox before enabling.',
    enabled: false,
    createdAt: '2026-03-07T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  {
    id: 'seed-yahoo',
    provider: 'Yahoo',
    label: 'Yahoo Primary',
    emailAddress: '',
    notes: 'Configure a real Yahoo seed inbox before enabling.',
    enabled: false,
    createdAt: '2026-03-07T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
  {
    id: 'seed-icloud',
    provider: 'iCloud',
    label: 'iCloud Primary',
    emailAddress: '',
    notes: 'Configure a real iCloud seed inbox before enabling.',
    enabled: false,
    createdAt: '2026-03-07T00:00:00Z',
    updatedAt: '2026-03-07T00:00:00Z',
  },
];

export const mockSeedRuns: SeedTestRunSummary[] = [
  {
    id: 'seedrun-demo',
    identityId: 'ws-info',
    identity: 'info@wheatandstone.ca',
    identityLabel: 'Brand Rail',
    messageId: 'msg-ws-seed',
    templateId: 'tpl-seed-lab',
    subject: 'TMail seed test probe',
    status: 'in_review',
    summary: '1/4 seed results recorded. 1 inbox, 0 spam.',
    resultCount: 4,
    completedCount: 1,
    acceptedCount: 1,
    rejectedCount: 0,
    inboxCount: 1,
    promotionsCount: 0,
    spamCount: 0,
    missingCount: 0,
    cleanCount: 1,
    issuesCount: 0,
    acceptanceScore: 100,
    placementScore: 100,
    renderScore: 100,
    overallScore: 25,
    scoreState: 'attention',
    createdAt: '2026-03-07T08:25:00Z',
    updatedAt: '2026-03-07T08:40:00Z',
    sentAt: '2026-03-07T08:25:00Z',
  },
];
